# Generated by Django 4.1.3 on 2022-12-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('doctor', models.CharField(max_length=12)),
            ],
        ),
    ]
