# Generated by Django 4.1.3 on 2022-12-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_iin',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_begin',
            field=models.TimeField(verbose_name='Begin time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_end',
            field=models.TimeField(verbose_name='Finish time'),
        ),
    ]
