# Generated by Django 4.1.3 on 2022-12-04 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_department_id_alter_doctor_experience_and_more'),
        ('appointment', '0002_rename_doctor_appointment_doctor_iin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_iin',
            field=models.CharField(max_length=12, verbose_name='Doctor IIN'),
        ),
    ]
