# Generated by Django 4.1.3 on 2022-12-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_department_id_alter_doctor_experience_and_more'),
        ('appointment', '0003_appointment_doc_alter_appointment_doctor_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
    ]
