# Generated by Django 4.1.3 on 2022-12-04 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department_id',
            field=models.IntegerField(verbose_name='Department ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(verbose_name='Years of experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9,9}$')], verbose_name='State ID number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='iin_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12,12}$')], verbose_name='IIN'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(verbose_name='Appointment price'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='special_id',
            field=models.IntegerField(verbose_name='Special ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9,9}$')], verbose_name='State ID number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='iin_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12,12}$')], verbose_name='IIN'),
        ),
    ]
